parserOptions:
  project: ./tsconfig.json # tsconfig.json path here
env:
  browser: true
  node: true
  jasmine: true
  es6: true
extends:
  - '@team-lab/eslint-config/typescript'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'